export const lightTheme = {
    mainBGColor: '#F7F6F9',
    mainTextColor: '#111111',
    secondaryBgColor: '#FFFFFF',
    secondaryTextColor: '#343434',
    mainAccentColor: '#3E85F3',
    mainAccentColorActive: '#2B78EF',
    secondaryAccentColor: '#DCEBF7',
    secondaryAccentColorActive: '#E3F3FF',
    backdropColor: '#00000080',
    sidebarMainActiveColor: '#3E85F3',
    sidebarBGColor: '#FFFFFF',
    sidebarTextColor: '#34343450',
    sidebarLogoTextColor: '#3E85F3',
    sidebarPanelColor: '#34343450',
    buttonTextColor: '#FFFFFF',
    borderContainerStatisticsColor: '#E3F3FF',
};

export const darkTheme = {
    mainBGColor: '#171820',
    mainTextColor: '#FFFFFF',
    secondaryBgColor: '#21222C',
    secondaryTextColor: '#FFFFFF',
    mainAccentColor: '#3E85F3',
    mainAccentColorActive: '#2B78EF',
    secondaryAccentColor: '#DCEBF7',
    secondaryAccentColorActive: '#3E85F3',
    backdropColor: '#00000080',
    sidebarMainActiveColor: '#FFFFFF',
    sidebarBGColor: '#13151A',
    sidebarTextColor: '#FFFFFF',
    sidebarLogoTextColor: '#E3F3FF',
    sidebarPanelColor: '#FAFAFA4D',
    buttonTextColor: '#FFFFFF',
    borderContainerStatisticsColor: 'rgb(227, 243, 255, 0.2)',
};