name: Pull request check

on:
  pull_request

jobs:
  build-vite-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install 🔧
        run: npm ci
      
      - name: Build 🔧
        run: npm run build
